base_folder:
  id: 35nE6fy4Uvg
conversion:
  mxEaku0YsO9:
    name: Période Enjeux
    tag: S0 (L1)
    image: select.png
  KpoKXH5QU6K:
    name: Mathématiques
    tag: Math0
  0vePwFm0CWl:
    name: Semestre 1
    tag: S1 (L1)
    image: maths.png
  Gzk3rcAZUW4:
    name: Fondements
    tag: MF1
  w3Q7kInAI7A:
    name: Approfondissements
    tag: MA1
  Q5093cvnf3Y:
    name: Electronique
    tag: EN1
  LpQkouV4cpD:
    name: "Bases de l'informatique"
    tag: BI1
tag_image:
  TD: TD.svg
  Amphi: Amphi.svg
  TP: TP.svg
